name: "Android Buildbotting Final Boss"

on:
  workflow_dispatch:
    inputs:
      repo_manifest:
        description: "Repo manifest"
        required: true
        type: string
      repo_branch:
        description: "Repo manifest's branch"
        required: true
        type: string
      local_manifest:
        description: "Personal local manifest [repository or raw]"
        required: true
        type: string
      local_branch:
        description: "Personal local manifest's branch (required for repository cloning)"
        required: false
        type: string
      device_name:
        description: "Device's codename"
        required: true
        type: string
      product_name:
        description: "Product to build"
        required: true
        type: string
      build_command:
        description: 'Command to be used for compiling'
        required: true
        default: 'mka bacon'
      build_type:
        description: 'Type of build'
        required: true
        default: 'userdebug'
        type: choice
        options: 
        - 'eng'
        - 'userdebug'
        - 'user'
      microg:
        description: 'Integrate microG (Linag only)'
        required: false
        type: boolean
      artifact:
        description: 'Output file to upload'
        required: true
        type: string
      missing:
        description: 'Allow missing dependencies'
        required: true
        type: boolean

permissions:
  contents: write

jobs:
  build:
    name: "Build Adrod"
    runs-on: ubuntu-slim
    steps:
        - name: "Checkout"
          uses: actions/checkout@v6

        - name: "Free disk space"
          uses: endersonmenezes/free-disk-space@v3  # Use @main for latest, @v3 for stable
          with:
            remove_android: false
            remove_dotnet: false
            remove_haskell: false
            remove_tool_cache: true
            remove_swap: true
            remove_packages: "mercurial powershell"
            remove_packages_one_command: true
            remove_folders: "/usr/share/az* /usr/local/lib/node_modules /usr/local/share/powershell /usr/local/aws-cli /usr/local/aws-sam-cli"
            rm_cmd: "rmz"  # Use 'rmz' for faster deletion (default: 'rm')
            rmz_version: "3.1.1"  # Required when rm_cmd is 'rmz'
            testing: false

        - name: "Set up dependencies"
          run: |
            sudo apt update
            sudo apt upgrade -y
            DEBIAN_FRONTEND=noninteractive sudo apt install -yq \
              bc bison build-essential ccache curl flex g++-multilib gcc-multilib git git-lfs gnupg gperf imagemagick protobuf-compiler python3-protobuf lib32readline-dev lib32z1-dev libdw-dev libelf-dev libgnutls28-dev \
              lz4 libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev
            wget https://archive.ubuntu.com/ubuntu/pool/universe/n/ncurses/libtinfo5_6.3-2_amd64.deb && sudo dpkg -i libtinfo5_6.3-2_amd64.deb && rm -f libtinfo5_6.3-2_amd64.deb
            wget https://archive.ubuntu.com/ubuntu/pool/universe/n/ncurses/libncurses5_6.3-2_amd64.deb && sudo dpkg -i libncurses5_6.3-2_amd64.deb && rm -f libncurses5_6.3-2_amd64.deb

        - name: "Set up swap"
          uses: thejerrybao/setup-swap-space@v1
          with:
            swap-space-path: /swapfile
            swap-size-gb: 16
            remove-existing-swap-files: true

        - name: "Set up adrod repo"
          run: |
            mkdir -p ~/bin
            mkdir ./adrodsrc
            curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
            chmod a+x ~/bin/repo
            export PATH="$HOME/bin:$PATH"
            git config --global user.name "github-actions[bot]"
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            cd ./adrodsrc
            repo init -u ${{ github.event.inputs.repo_manifest }} -b ${{ github.event.inputs.repo_branch }} --depth=1 --git-lfs --no-clone-bundle
            if [ -n "${{ github.event.inputs.local_branch }}" ]; then
              git clone --depth=1 ${{ github.event.inputs.local_manifest }} -b ${{ github.event.inputs.local_branch }} .repo/local_manifests
            else
              curl -o .repo/local_manifests/local_manifest.xml ${{ github.event.inputs.local_manifest }} --create-dirs
            fi
            repo sync -j8

        - name: "Set up ccache"
          uses: hendrikmuhs/ccache-action@v1.2

        - name: "Display remaining disk space"
          run: |
            df -h /

        - name: "Build adrod!"
          timeout-minutes: 330
          run: |
            cd ./adrodsrc
            if [ ${{ github.event.inputs.missing }} = true ]; then
              export ALLOW_MISSING_DEPENDENCIES=true
            fi
            if [ ${{ github.event.inputs.microg }} = true ]; then
              git clone --depth=1 https://github.com/lineageos4microg/android_vendor_partner_gms.git -b master vendor/partner_gms
              export WITH_GMS=true
            fi
            source build/envsetup.sh
            lunch ${{ github.event.inputs.product_name }}-${{ github.event.inputs.build_type }}
            ${{ github.event.inputs.build_command }} -j8

        - name: "To GitHub Artifacts"
          uses: actions/upload-artifact@v7
          with:
            name: "${{ github.event.inputs.product_name }}-${{github.run_id}}-artifacts"
            path: adrodsrc/out/target/product/${{ github.event.inputs.device_name }}/${{ github.event.inputs.artifact }}
