name: Kranal Bilder
on:
  workflow_dispatch:
    inputs:
      release:
        description: "Release"
        default: false
        type: boolean

jobs:
  build:
    name: Bild kranal
    runs-on: ubuntu-latest

    steps:
    - name: Check out
      uses: actions/checkout@v6
 
    - name: Set up environment
      run: |
        echo "BUILD_TIME=$(TZ=Asia/Jakarta date "+%Y%m%d-%H%M%S")" >> $GITHUB_ENV
        sudo apt update

    - name: "Free disk space"
      uses: endersonmenezes/free-disk-space@v3
      with:
        remove_android: true
        remove_dotnet: true
        remove_haskell: true
        remove_tool_cache: true
        remove_swap: true
        remove_packages: "azure-cli google-cloud-cli microsoft-edge-stable google-chrome-stable firefox postgresql* temurin-* *llvm* mysql* dotnet-sdk-* clang* apache2* php* gfortran* nginx* docker*"
        remove_packages_one_command: true
        remove_folders: "/usr/share/swift /usr/share/miniconda /usr/share/az* /usr/local/lib/node_modules /usr/local/share/chromium /usr/local/share/powershell /usr/local/julia /usr/local/aws-cli /usr/local/aws-sam-cli /usr/share/gradle /usr/local/lib/lein /usr/share/java/selenium-server.jar"
        rm_cmd: "rmz"
        rmz_version: "3.1.1"
        testing: false
 
    - name: Set up dependencies
      run: |
        sudo apt upgrade -y
        sudo apt install -yq automake flex lzop bison gperf build-essential zip curl zlib1g-dev g++-multilib libxml2-utils bzip2 \
          libbz2-dev libbz2-1.0 libghc-bzlib-dev squashfs-tools pngcrush schedtool dpkg-dev liblz4-tool make optipng maven libssl-dev \
          pwgen libswitch-perl policycoreutils minicom libxml-sax-base-perl libxml-simple-perl bc libc6-dev-i386 lib32ncurses-dev libx11-dev \
          lib32z-dev libgl1-mesa-dev xsltproc unzip device-tree-compiler rename libelf-dev dwarves linux-modules-extra-$(uname -r)
        mkdir -p $GITHUB_WORKSPACE/kernel_workspace

    - name: "Set up zram"
      run: |
        sudo modprobe zram
        totalmem=$(LC_ALL=C free | grep -e "^Mem:" | sed -e 's/^Mem: *//' -e 's/  *.*//')
        mem=$((totalmem * 2 * 1024))
        sleep 1
        sudo zramctl /dev/zram0 -s $mem -a lz4
        sudo mkswap /dev/zram0
        sudo swapon -p 100 /dev/zram0

    - name: Download AOSP Clang
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace
        CLANG_URL="https://github.com/ravindu644/Android-Kernel-Tutorials/releases/download/toolchains/clang-r563880c.tar.gz"
        wget -O clang.tar.gz "$CLANG_URL"
        mkdir clang
        tar -C clang/ -xvf clang.tar.gz
        rm -rf clang.tar.gz
        
    - name: Download the kernel source code
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace
        git clone https://github.com/samsung-sm6225-dev/android_kernel_samsung_a05s -b android13-5.15 android-kernel --depth=1

    - name: Build kernel
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
        export PATH=$GITHUB_WORKSPACE/kernel_workspace/clang/bin:$PATH
        export KBUILD_BUILD_HOST=AITARAK
        export KBUILD_BUILD_USER=$(echo ${{ github.actor }} | tr A-Z a-z)
        make -j$(nproc --all) O=out ARCH=arm64 LLVM=1 vendor/m269-gki_defconfig
        make -j$(nproc --all) O=out ARCH=arm64 LLVM=1
        make -j$(nproc --all) O=out ARCH=arm64 LLVM=1 INSTALL_MOD_STRIP=1 INSTALL_MOD_PATH=$GITHUB_WORKSPACE/kernel_workspace/modules modules_install

    - name: Check the kernel compilation results
      run: |
       cd $GITHUB_WORKSPACE/kernel_workspace
       if [ -f android-kernel/out/arch/arm64/boot/Image ]; then
           echo "CHECK_FILE_IS_OK=true" >> $GITHUB_ENV
       else
           echo "Kernel output file is empty or broken."
           exit 1
       fi
  
    - name: Package kernel modules
      if: env.CHECK_FILE_IS_OK == 'true'
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace/modules
        mkdir staging
        cp -t staging/ $(find -type f -name "*.ko")
        cd staging
        rm zram.ko zsmalloc.ko || true
        tar -czf modules.tar.gz *.ko
        if [ -f ./modules.tar.gz ]; then
           echo "KMOD_IS_OK=true" >> $GITHUB_ENV
        else
           echo "Kernel modules output file is empty or broken."
           exit 1
        fi

    - name: Upload kernel image
      if: env.CHECK_FILE_IS_OK == 'true'
      uses: actions/upload-artifact@v7
      with:
        name: Image-a05s-${{ env.BUILD_TIME }}
        path: kernel_workspace/android-kernel/out/arch/arm64/boot/Image
        if-no-files-found: error

    - name: Upload kernel modules
      if: env.CHECK_FILE_IS_OK == 'true' && env.KMOD_IS_OK == 'true'
      uses: actions/upload-artifact@v7
      with:
        name: modules-${{ env.BUILD_TIME }}
        path: kernel_workspace/modules/staging/modules.tar.gz
        if-no-files-found: error

    - name: Release
      uses: softprops/action-gh-release@v3
      if: github.event.inputs.release == 'true'
      with:
        tag_name: ${{ env.BUILD_TIME }}
        draft: true
        prerelease: false
        working_directory: kernel_workspace
        token: ${{ secrets.PAT }}
        repository: samsung-sm6225-dev/android_kernel_samsung_a05s
        files: |
          android-kernel/out/arch/arm64/boot/Image
          modules/staging/modules.tar.gz
